#!/usr/bin/env python3
"""Prepare the homopolymer URP/VK1 validation figures for publication.

The source plots are internally authored vector PDFs produced during model
development.  This script converts them to SVG without changing the plotted
data, labels, or aspect ratio.  It does not rerun the SCFT inverse calculations.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path


MONTE_CARLO = Path(__file__).resolve().parents[1]
PAPER = MONTE_CARLO.parent
OUTPUT = MONTE_CARLO / "results/homopolymer_urp_vk1_validation"

FIGURES = (
    (
        PAPER
        / "figures/accuracy_saddle_approx/"
        "accuracy_saddle_approx-eps-converted-to.pdf",
        OUTPUT / "urp_vk1_error_map.svg",
    ),
    (
        PAPER
        / "figures/iw_saddle_approx/"
        "iw_saddle_approx-eps-converted-to.pdf",
        OUTPUT / "urp_vk1_saddle_profile.svg",
    ),
)

SOURCE_FILES = (
    (
        "accuracy_saddle_approx",
        (
            "accuracy_saddle_approx-eps-converted-to.pdf",
            "error_K_L_a0.01.dat",
            "error_K_L_a0.8.dat",
            "error_K_a_L0.5.dat",
            "error_K_a_L8.dat",
            "data_source.txt",
            "plot.py",
        ),
    ),
    (
        "iw_saddle_approx",
        (
            "iw_saddle_approx-eps-converted-to.pdf",
            "phitype5_L3_a0.5_b1_c1.mat",
            "input_phitype5.txt",
            "data_source.txt",
            "plot.py",
        ),
    ),
)


def main() -> None:
    converter = shutil.which("pdftocairo")
    if converter is None:
        raise RuntimeError("pdftocairo is required to convert the source PDFs")

    OUTPUT.mkdir(parents=True, exist_ok=True)
    for source, destination in FIGURES:
        if not source.is_file():
            raise FileNotFoundError(source)
        subprocess.run(
            [converter, "-svg", str(source), str(destination)],
            check=True,
        )

    for directory, filenames in SOURCE_FILES:
        source_directory = PAPER / "figures" / directory
        destination_directory = OUTPUT / "source" / directory
        destination_directory.mkdir(parents=True, exist_ok=True)
        for filename in filenames:
            source = source_directory / filename
            if not source.is_file():
                raise FileNotFoundError(source)
            shutil.copyfile(source, destination_directory / filename)

    readme = """# Homopolymer URP/VK1 validation figures

These SVGs are direct vector conversions of the homopolymer URP/VK1
validation plots used as Figures 1 and 2 in the present manuscript:

- `urp_vk1_error_map.svg`: relative error of prescribed-density saddle-field
  closures over amplitude and wavenumber.
- `urp_vk1_saddle_profile.svg`: the saddle potential generated by the
  prescribed modulated density II; the inset is the imposed density.

The main curves in the second figure are auxiliary-potential profiles, not
independently relaxed density profiles.  The conversion preserves the source
plot and uses `pdftocairo -svg`.  `source/` contains the source vector PDFs,
numerical `.dat`/`.mat` inputs, run input for density II, data-source notes, and
model-development plotting scripts.  Those Python scripts use legacy local imports
and are archived for provenance; the publication SVGs are reproduced directly
from the included vector PDFs.
"""
    (OUTPUT / "README.md").write_text(readme, encoding="utf-8")
    print(f"prepared {len(FIGURES)} homopolymer URP/VK1 figures in {OUTPUT}")


if __name__ == "__main__":
    main()
